self.supermarket = Supermarket()
        self.supermarket.add_product(Product("Apple", 1.0))
        self.supermarket.add_product(Product("Banana", 0.5))
        self.supermarket.add_product(Product("Orange", 1.5))
        self.supermarket.add_product(Product("Milk", 2.0))
        self.supermarket.add_product(Product("Bread", 1.0))
        self.supermarket.add_product(Product("Butter", 1.0))
        self.supermarket.add_product(Product("Cheese", 2.0))
        self.supermarket.add_product(Product("Eggs", 1.0))
        self.supermarket.add_product(Product("Yogurt", 1.0))
        self.supermarket.add_product(Product("Water", 0.5))
        self.supermarket.add_product(Product("Beer", 1.0))
        self.supermarket.add_product(Product("Wine", 2.0))
        self.supermarket.add_product(Product("Whiskey", 3.0))
        self.supermarket.add_product(Product("Vodka", 2.0))
        self.supermarket.add_product(Product("Rum", 2.0))
        self.supermarket.add_product(Product("Tequila", 2.0))
        self.supermarket.add_product(Product("Gin", 2.0))
        self.supermarket.add_product(Product("Coca Cola", 1.0))
        self.supermarket.add_product(Product("Pepsi", 1.0))
        self.supermarket.add_product(Product("Fanta", 1.0))
        self.supermarket.add_product(Product("Sprite", 1.0))
        self.supermarket.add_product(Product("7up", 1.0))
        self.supermarket.add_product(Product("Mountain Dew", 1.0))
        self.supermarket.add_product(Product("Dr. Pepper", 1.0))
        self.supermarket.add_product(Product("Root Beer", 1.0))
        self.supermarket.add_product(Product("Ginger Ale", 1.0))
        self.supermarket.add_product(Product("Tonic Water", 1.0))
        self.supermarket.add_product(Product("Soda Water", 1.0))
        self.supermarket.add_product(Product("Lemonade", 1.0))
        self.supermarket.add_product(Product("Iced Tea", 1.0))